# Generated by Django 6.0.6 on 2026-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='to_do_model',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
